import { beforeEach, describe, expect, it, vi } from 'vitest';

const { findManyExpense, getOwnerContext } = vi.hoisted(() => ({
  findManyExpense: vi.fn(),
  getOwnerContext: vi.fn(),
}));

vi.mock('@/lib/prisma', () => ({
  default: {
    expense: { findMany: findManyExpense },
  },
}));

vi.mock('@/lib/server/get-owner-context', () => ({
  getOwnerContext,
}));

import { GET } from './route';

const ownerContext = {
  ownerType: 'user' as const,
  ownerId: 1,
  ownerFilter: { user_id: 1, house_id: null },
  role: 'owner' as const,
};

describe('GET /api/expenses/recent', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    getOwnerContext.mockResolvedValue(ownerContext);
    findManyExpense.mockResolvedValue([]);
  });

  it('excludes expenses generated by loan payments from the gastos feed', async () => {
    const response = await GET(
      new Request(
        'http://localhost/api/expenses/recent?limit=25',
      ) as Parameters<typeof GET>[0],
    );

    expect(response.status).toBe(200);
    expect(findManyExpense).toHaveBeenCalledWith(
      expect.objectContaining({
        where: expect.objectContaining({
          user_id: 1,
          house_id: null,
          is_paid: true,
          loan_payment_id: null,
        }),
      }),
    );
  });
});
