
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` does not open a connection. A placeholder keeps postinstall
// and predev working when DATABASE_URL is unset. CI and local .env still win.
const databaseUrl =
  process.env.DATABASE_URL ??
  "postgresql://prisma:prisma@127.0.0.1:5432/prisma";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'tsx ./prisma/seed.ts',
  },
  datasource: {
    url: databaseUrl,
  },
});
