export const PLAN_COPY = {
  tabLiquidity: 'Liquidez',
  tabPlan: 'Plan',
  tabListLabel: 'Liquidez y plan',
  shortfallTitle: 'Plan para cubrir el hueco',
  surplusTitle: 'Dónde conviene el extra',
  balancedTitle: 'Este periodo cuadra',
  balancedBody: 'Con lo que entra y lo que toca pagar, este periodo cierra.',
  heroHint: 'Con lo que hay en este periodo, esta es la ruta con menor costo y riesgo estimado.',
  horizonLabel: 'Horizonte',
  fortnight: 'Quincena',
  month: 'Mes',
  avalanche: 'Avalancha',
  snowball: 'Bola de nieve',
  strategyLabel: 'A dónde va el extra',
  why: 'Por qué esta ruta',
  choose: 'Elegir esta ruta',
  apply: 'Aplicar pasos',
  checklistTitle: 'Pasos de esta ruta',
  checklistHint: 'Márcalos aquí. Todavía no se crean pagos en MiCasa.',
  retry: 'Reintentar',
  emptyTitle: 'Todavía no hay cuentas u obligaciones para armar un plan',
  emptyBody: 'Cuando tengas efectivo o pagos en este periodo, aquí ves qué hacer con el hueco o con el extra.',
  emptyCta: 'Ir a cuentas',
  gapHow: 'Cómo sale este número',
  gapLabel: 'Hueco',
  extraLabel: 'Extra',
  tieTitle: 'Estas dos rutas salen parecidas',
  tieBody: 'Elige si te importa más pagar menos intereses o correr menos riesgo.',
  preferCost: 'Menor costo',
  preferRisk: 'Menor riesgo',
  bridgeTitle: 'Simular préstamo puente',
  consolidateTitle: 'Simular consolidación',
  simDisclaimer: 'Es una simulación con los números que tú pongas. No es una aprobación de crédito.',
  simPending: 'Llena tasa, plazo y comisión para ver esta simulación.',
  rate: 'Tasa anual (%)',
  term: 'Plazo (meses)',
  fee: 'Comisión (%)',
  lowConfidence: 'Faltan datos para afinar la ruta. Los números de abajo no inventan una tasa tuya.',
  noSafePrimary: 'No hay una ruta principal que deje intactos renta, servicios, seguros y nómina. Si ves otra abajo, es una alternativa con riesgo alto.',
  estimatedCost: 'Costo estimado',
  gapClosed: 'Cierra',
  monthsSaved: 'Meses',
  interestSaved: 'Intereses',
  loading: 'Armando el plan',
} as const;
